const product = [
    {
        name: 'Amazon prime',
        price: 20,
        image:'./image/product/amazon-prime.png',
        slug:'amazon-prime',
        catagory:'Music',
        desciption:'Amazon__prime',
        rating: 4.5,
        review: 20,
        stock:50,
        Brand: 'amazon',
        totalSale: 50
    },
    {
        name: 'Cats',
        price: 200,
        image:'./image/product/cats.png',
        slug:'cats',
        catagory:'shoe',
        desciption:'Stylish Cats',
        rating: 5,
        review: 100,
        stock:75,
        Brand: 'Bata',
        totalSale: 120,
    },
    {
        name: 'Hand Bag',
        price: 40,
        image:'./image/product/handBag.png',
        slug:'handBag',
        catagory:'bag',
        desciption:'hand__Bag',
        rating: 4,
        review: 30,
        stock:55,
        Brand: 'Apex',
        totalSale: 30,
    },
    {
        name: 'Cup',
        price: 10,
        image:'./image/product/cup.png',
        slug:'cup',
        catagory:'cocaris',
        desciption:'Coffee_cup',
        rating: 5,
        review: 40,
        stock:65,
        Brand: 'RFL',
        totalSale: 85,
    },
    {
        name: 'Shoe',
        price: 5,
        image:'./image/product/shoe.png',
        slug:'shoe',
        catagory:'shoes',
        desciption:'wonderful_shoe',
        rating: 5,
        review: 45,
        stock:95,
        Brand: 'walker',
        totalSale: 85,
    },
    {
        name: 'Travel Bag',
        price: 5,
        image:'./image/product/travelBag.png',
        slug:'t-bag',
        catagory:'bags',
        desciption:'wonderful Travel bag',
        rating: 5,
        review: 45,
        stock:95,
        Brand: 'Kazi lether',
        totalSale: 95,
    },
    {
        name: 'Digital Watch',
        price: 25,
        image:'./image/product/digitalWatch.png',
        slug:'digital-watch',
        catagory:'digitalWatch',
        desciption:'wonderful watch',
        rating: 5,
        review: 45,
        stock:95,
        Brand: 'Armani',
        totalSale: 96,
    },
    {
        name: 'Trolly Bag',
        price: 35,
        image:'./image/product/trolly.png',
        slug:'trolly-bag',
        catagory:'trolly',
        desciption:'wonderful trolly bag',
        rating: 4.5,
        review: 45,
        stock:65,
        Brand: 'Kazi lether',
        totalSale: 55,
    },
]

module.exports = product